[paths]
output = "freedom"
source = [".", "Polyweb", "Polyweb/Polynet"]
artifact = "obj"
install = "/usr/local/bin"

[options]
compilation-flags = "-Wall -std=c++17 -O3 -pthread"
libraries = ["sqlite3", "ssl", "crypto"]

[env.OS.Windows_NT.options]
compilation-flags = "-Wall -std=c++17 -O3 -pthread -static-libgcc -static-libstdc++"
libraries = ["sqlite3", "ssl", "crypto", "z", "ws2_32", "crypt32"]
static = true
